import { createFeatureSelector, createSelector } from '@ngrx/store';
import { turniFeatureKey, TurniState } from './turni.reducer';
import { calculateWorkerStats, defaultShiftDefinitions } from '../utils/schedule-engine.utils';

export const selectTurniState = createFeatureSelector<TurniState>(turniFeatureKey);
export const selectLoading = createSelector(selectTurniState, s => s.loading);
export const selectError = createSelector(selectTurniState, s => s.error);
export const selectWorkers = createSelector(selectTurniState, s => s.workers);
export const selectPlanCache = createSelector(selectTurniState, s => s.planCache);
export const selectCurrentRange = createSelector(selectTurniState, s => s.currentRange);
export const selectPlan = createSelector(selectPlanCache, selectCurrentRange, (cache, range) => range ? cache[range.key] ?? null : null);
export const selectDays = createSelector(selectPlan, p => p?.days ?? []);
export const selectIssues = createSelector(selectTurniState, s => s.issues);
export const selectAudits = createSelector(selectTurniState, s => s.audits);
export const selectOptimizer = createSelector(selectTurniState, s => s.optimizer);
export const selectErrors = createSelector(selectIssues, issues => issues.filter(i => i.severity === 'ERROR'));
export const selectWarnings = createSelector(selectIssues, issues => issues.filter(i => i.severity === 'WARNING'));
export const selectInfos = createSelector(selectIssues, issues => issues.filter(i => i.severity === 'INFO'));
export const selectCanPublish = createSelector(selectPlan, selectErrors, (p, e) => !!p && p.status === 'DRAFT' && e.length === 0);
export const selectRangeKeys = createSelector(selectPlanCache, cache => Object.keys(cache).sort());
export const selectIsWeekMode = createSelector(selectCurrentRange, r => r?.mode === 'WEEK');
export const selectIsMonthMode = createSelector(selectCurrentRange, r => r?.mode === 'MONTH');
export const selectWorkerMap = createSelector(selectWorkers, workers => new Map(workers.map(w => [w.id, w])));
export const selectWorkerStats = createSelector(selectPlan, selectWorkers, (plan, workers) => calculateWorkerStats(plan, workers, defaultShiftDefinitions));
